/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import DatabaseManager.databaseManager;
import beanClasses.patientBean;
import java.awt.event.ActionEvent;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Ammar
 */
public class Patient extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    public Patient() {
        initComponents();
        getPatient();
        pITF.setEditable(false);
    }
    private void getPatient(){
    try{
        Vector v=databaseManager.getPatient();
        patientNL.setListData(v);
    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    }
    }//end Customer  
      public void actionPerformed(ActionEvent e){
        if(e.getSource()==addButton)
            addRecord();
        if(e.getSource()==backButton){
         hide();
         } 
        if(e.getSource()==clearButton)
            clear();
    }
    private void clear(){
        pITF.setText("");
        pNTF.setText("");
        ageTF.setText("");
        sexTF.setText("");
        cnicTF.setText("");
        addressTF.setText("");
        contactTF.setText("");
        bGTF.setText("");
        dORTF.setText("");
        aDTF.setText("");
        rRTF.setText("");
        remarksTF.setText("");
        
    }// end clear
 private void addRecord(){
            String  patientName    = pNTF.getText();
            int     age            = Integer.parseInt(ageTF.getText());
            String  sex            = sexTF.getText();
            int     cnic           = Integer.parseInt(cnicTF.getText());
            int     contact        = Integer.parseInt(contactTF.getText());
            String  address        = addressTF.getText();
            String  bloodGroup     = bGTF.getText();
            String  dateOfRelease  = dORTF.getText();
            String  admitDate      = aDTF.getText();
            String  releaseReason  = rRTF.getText();
            String  remarks        =remarksTF.getText();
            try{
                int rows=databaseManager.addPatient(patientName,age,sex,cnic,contact,address,bloodGroup,dateOfRelease,admitDate,releaseReason,remarks);
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"RECORD INSERTED ");
                clear();
                getPatient();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
    }//end addRecord
    private void updateRecord(){
         patientBean bean=(patientBean)patientNL.getSelectedValue();
         if(bean==null)return ;
            String  patientName    = pNTF.getText();
            int     age            = Integer.parseInt(ageTF.getText());
            String  sex            = sexTF.getText();
            int     cnic           = Integer.parseInt(cnicTF.getText());
            int     contact        = Integer.parseInt(contactTF.getText());
            String  address        = addressTF.getText();
            String  bloodGroup     = bGTF.getText();
            String  dateOfRelease  = dORTF.getText();
            String  admitDate      = aDTF.getText();
            String  releaseReason  = rRTF.getText();
            String  remarks        =remarksTF.getText();
         try{
          int rows=databaseManager.updatePatient(bean.getPatientId(),patientName,age,sex,cnic,contact,address,bloodGroup,dateOfRelease,admitDate,releaseReason,remarks);
            
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"RECORD UPDATED ");
                clear();
                getPatient();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         }//end updateRecord
    private void deleteRecord(){
    patientBean bean = (patientBean)patientNL.getSelectedValue();
    if(bean==null)return;
    try{
        int rows = databaseManager.deletePatient(bean.getPatientId());
          if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+" RECORD DELETED ");
                clear();
                getPatient();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
         } //end deleteRecord
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        remarksTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientNL = new javax.swing.JList();
        pITF = new javax.swing.JTextField();
        pNTF = new javax.swing.JTextField();
        sexTF = new javax.swing.JTextField();
        cnicTF = new javax.swing.JTextField();
        contactTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        bGTF = new javax.swing.JTextField();
        dORTF = new javax.swing.JTextField();
        aDTF = new javax.swing.JTextField();
        rRTF = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("REMARKS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 530, 70, 17);

        remarksTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(remarksTF);
        remarksTF.setBounds(200, 520, 490, 80);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("       PATIENT ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 80, 120, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("PATIENT NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 60, 130, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("SEX");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 200, 50, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("CNIC");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 240, 50, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("CONTACT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 280, 80, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("ADDRESS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 320, 80, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("   BLOOD GROUP");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 360, 130, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("DATE OF RELEASE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 400, 140, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("         ADMIT DATE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 440, 130, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("RELEASE REASON");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 480, 140, 30);

        patientNL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        patientNL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                patientNLValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(patientNL);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(500, 80, 190, 430);

        pITF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(pITF);
        pITF.setBounds(200, 80, 290, 30);

        pNTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(pNTF);
        pNTF.setBounds(200, 120, 290, 30);

        sexTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(sexTF);
        sexTF.setBounds(200, 200, 290, 30);

        cnicTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(cnicTF);
        cnicTF.setBounds(200, 240, 290, 30);

        contactTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(contactTF);
        contactTF.setBounds(200, 280, 290, 30);

        addressTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(addressTF);
        addressTF.setBounds(200, 320, 290, 30);

        bGTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(bGTF);
        bGTF.setBounds(200, 360, 290, 30);

        dORTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(dORTF);
        dORTF.setBounds(200, 400, 290, 30);

        aDTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(aDTF);
        aDTF.setBounds(200, 440, 290, 30);

        rRTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(rRTF);
        rRTF.setBounds(200, 480, 290, 30);

        addButton.setBackground(new java.awt.Color(255, 51, 255));
        addButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(200, 610, 80, 40);

        updateButton.setBackground(new java.awt.Color(255, 51, 255));
        updateButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(290, 610, 87, 40);

        deleteButton.setBackground(new java.awt.Color(255, 51, 255));
        deleteButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(390, 610, 85, 40);

        clearButton.setBackground(new java.awt.Color(255, 51, 255));
        clearButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(490, 610, 79, 40);

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(580, 610, 110, 40);

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel2.setText("PATIENT ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-20, 140, 90, 30);

        jLabel13.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel13.setText("PATIENT ");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(100, 10, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(190, 0, 310, 60);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("PATIENT NAME");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(80, 120, 120, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("PATIENT NAME");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 120, 120, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("AGE");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(150, 160, 50, 30);

        ageTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(ageTF);
        ageTF.setBounds(200, 160, 290, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        addRecord();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateRecord();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteRecord();

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        hide();
    }//GEN-LAST:event_backButtonActionPerformed

    private void patientNLValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_patientNLValueChanged
        // TODO add your handling code here:
          patientBean bean=(patientBean)patientNL.getSelectedValue();
       if(bean==null)return;
       
       pITF.setText(""+bean.getPatientId());
       pNTF.setText(bean.getPatientName());
       ageTF.setText(""+bean.getAge());
       sexTF.setText(bean.getSex());
       cnicTF.setText(""+bean.getCnic());
       contactTF.setText(""+bean.getContact());
       addressTF.setText(""+bean.getAddress());
       bGTF.setText(bean.getBloodGroup());
       dORTF.setText(""+bean.getDateOfRelease());
       aDTF.setText(""+bean.getAdmitDate());
       rRTF.setText(""+bean.getReleaseReason());
       remarksTF.setText(bean.getRemarks());
    }//GEN-LAST:event_patientNLValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aDTF;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addressTF;
    private javax.swing.JTextField ageTF;
    private javax.swing.JTextField bGTF;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField cnicTF;
    private javax.swing.JTextField contactTF;
    private javax.swing.JTextField dORTF;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pITF;
    private javax.swing.JTextField pNTF;
    private javax.swing.JList patientNL;
    private javax.swing.JTextField rRTF;
    private javax.swing.JTextField remarksTF;
    private javax.swing.JTextField sexTF;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
